# Generated by Django 5.0.2 on 2024-03-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olymp_name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('olymp_date_start', models.DateField(verbose_name='Дата проведения')),
                ('olymp_time', models.TimeField(verbose_name='Длительность')),
            ],
        ),
    ]
