# Generated by Django 5.0.2 on 2024-05-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.IntegerField(choices=[(0, 'В ожидании'), (1, 'Принята'), (2, 'Отклонена')], default=0),
        ),
    ]
