# Generated by Django 5.0.2 on 2024-05-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0005_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.IntegerField(choices=[(0, 'В ожидании'), (1, 'Принята'), (2, 'Отклонена')], default=0, verbose_name='Статус заявки'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='Название образовательной организации')),
                ('school_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions', to='olymp.subdivision', verbose_name='Местоположение')),
            ],
        ),
    ]
