# Generated by Django 5.0.2 on 2024-10-19 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0006_alter_application_application_status_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_participate',
        ),
        migrations.AddField(
            model_name='application',
            name='course_participate',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Класс участия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
