# Generated by Django 5.0.2 on 2024-10-31 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0008_country_student_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='application_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_olymp',
            new_name='olymp',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='course_participate',
            new_name='participate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='application_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_student',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='olymp.school', verbose_name='Общеобразовательная организация'),
        ),
        migrations.AddField(
            model_name='application',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='olymp.person', verbose_name='Учитель'),
        ),
    ]
