# Generated by Django 5.0.2 on 2024-11-02 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0010_application_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='olymp.employee', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.IntegerField(choices=[(0, 'Организатор'), (1, 'Представитель муниципалитета'), (2, 'Учитель')], default=0),
        ),
    ]
