# Generated by Django 5.0.2 on 2024-11-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0012_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], default=0, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
